### ISSUE TITLE
Error running Mist wallet

### ISSUE THREAD

**Issue by sjmackenzie** [ethereumproject/go-ethereum#161] opened 2017-03-13 16:16 UTC
## Steps to replicate
* start geth [v3.3.0](https://github.com/ethereumproject/go-ethereum/releases/tag/v3.3.0)
* let geth sync
* open 0.9.1 Mist wallet after geth sync

## Expected behaviour
* wallet runs normally

## Actual behaviour
* error message "Error running downloaded binary" is displayed 
* user said:
```
"It looks like its not scanning resources eg not finding geth is already running"
```
```
"Tried [restarting Mist]. Still would not detect geth was already running"
```
* user's screenshot (notice the error message on the splash screen)
![wp_20170313_15_52_05_pro](https://cloud.githubusercontent.com/assets/158321/23862877/276403d2-0849-11e7-96d1-573a29b39a70.jpg)

## Workaround
* rollback to previous version of geth

**Comment by pascaldekloe** [comment] 2017-03-17 17:08
We are unable to reproduce this problem. Help wantend!

**Comment by Shumkar** [comment] 2017-03-20 19:10
I confirm. I have the same issue. What help do you need? My OS is Win 7 x64.

**Comment by pascaldekloe** [comment] 2017-03-21 09:55
@splix thinks it's RPC related. Can you verify that the data transfer works @Shumkar?

**Comment by pascaldekloe** [comment] 2017-03-21 10:00
Closing this one as dupe of #151

**Closed by pascaldekloe** 2017-03-21 10:00 UTC
Labels: status/help wanted

**Comment by Shumkar** [comment] 2017-03-21 12:23
Ethereum Classic Wallet 0.9.1 seems to be unable to detect the presence of Geth neither in its resources/geth folder nor in Windows processes. 

It says "Error running downloaded binary" in all 3 cases: there is no Geth in this folder; there is Geth but it is not launched; there is Geth and it's launched. 

If I understand correctly, in the 1st case it should download Geth; in the 2nd it should launch it; in the 3rd it should connect to it. But it don't. 

When I switch to Ethereum Classic Wallet 0.8.1, it works (very sloooowly but I think it's another issue).

**Comment by wdiwng1** [comment] 2018-04-19 04:43
我也是WIN7系统。运行mist的时候同样出现了error  running  downloaded  binary，请问应该怎么解决这个问题？
