### ISSUE TITLE
cannot sync data

### ISSUE THREAD

**Issue by SalleryWang** [ethereumproject/go-ethereum#724] opened 2019-08-23 09:40 UTC
always 0 peers
2019-08-23 17:38:09 Discover                                                                 0/25 peers
2019-08-23 17:39:09 Discover                                                                 0/25 peers

**Comment by soc1c** [comment] 2019-08-23 16:25
duplicate of https://github.com/etclabscore/go-ethereum/issues/49

**Closed by soc1c** 2019-08-23 16:25 UTC
