### ISSUE TITLE
Constantly downloading block #1920000

### ISSUE THREAD

**Issue by yt-bg** [ethereumproject/go-ethereum#9] opened 2016-07-29 00:03 UTC
I have built geth from the source (git cloned at 28 jul, 01:09).
I have the full blockchain downloaded.
BUT
geth is constantly warning about  Bad block #1920000, and worse - it is filling my download channel almost to 100%.
Before I reached the last block this was rare event.
Applying screenshot - on the top is RX 1.54MiB/s, on the bottom TX ~50KiB/s. 

![geth_traffic](https://cloud.githubusercontent.com/assets/9059665/17233394/26944e54-5538-11e6-8d3b-b10e6d467fa4.png)

UPDATE
---------
The full download channel event lasted for an hour.
Now the warnings are still there but maybe this traffic is from the blocks. At the beginning I downloaded them in batches of 2048 (maybe compressed) and the traffic was very low.

UPDATE 2
-----------
Now I had peaceful period - 60 blocks without the warning and the traffic is low.
Attaching log.

[geth.log.txt](https://github.com/ethereumproject/go-ethereum/files/389675/geth.log.txt)

UPDATE 3
-----------
As I am watching both the log and the traffic graph I can say - there is strong correlation between the warning "Bad block #1920000" and a traffic spike.

How a traffic spike looks:
![geth_traffic_2](https://cloud.githubusercontent.com/assets/9059665/17238925/975595fa-5568-11e6-9b90-9c6fe147a8bf.jpg)

**Comment by whatisgravity** [comment] 2016-07-29 15:22
Thanks for this report, the detail will make it much easier to solve, these edge issues are important to know about.

**Comment by whatisgravity** [comment] 2016-07-30 11:46
So my suspicion is this is a result of using only BadHashes to prevent syncing on the wrong chain, which creates a loop. You reject the block but then receive it again from the same or similar peer.

**Comment by yt-bg** [comment] 2016-07-30 21:25
Thank you for your work. Keep ETC strong.

**Comment by russdirks** [comment] 2016-08-03 03:14
I'll jump in here because I think I might be experiencing the same issue.

I've been solo mining for about 3 months now, with no problems.  After the HF I upgraded to the Classic version of geth.exe once it became available.  Since then I've been  experiencing the following problems:

* My internet usage has more than doubled.  Pre-HF it was about 4GB/day, now it is up to 11 GB/day. 
* Quite often (20 - 30 times per day), my node stops receiving newly mined blocks from the rest of the network.  These outages last typically between 5 - 15 minutes, after which time it re-syncs with the network.
* in the log file, every 2 or 3 minutes a message displays...
    _Bad block #1920000,  Found known bad hash in chain 4985f5ca3d2afbec36529aa96f74de3cc10a2a4a6c44f2157a57d2c6059a11bb_
* My peerCount is all over the map.  One minute it will be at the max (25), and a few minutes later it will be down to 3, or anywhere in between.

Let me know if there is any more information I can give you.

**Comment by whatisgravity** [comment] 2016-08-03 05:31
Thank you for providing additional information. Are you able to sync when manually specifying bootstrap nodes using --bootnodes? 

As I said in the thread, we will need to disconnect peers offering the divergent block hash, and we will need to build a tool to check the volunteer bootstrap nodes and confirm they are providing peers from the ETC network.

I know disconnecting peers will fix the issue, but I believe knowing why you are receiving peers from the divergent chain is also important.

**Comment by russdirks** [comment] 2016-08-03 21:24
I thought the latest version of geth had the new volunteer bootstrap nodes hard coded in?  

I switched back to the EF version of geth and it is running very stable.  I would like to run it for a full 24 hour cycle, and then I will try the classic version again with the --bootnodes option to see if I can get it to run stable.

**Comment by russdirks** [comment] 2016-08-05 02:53
I switched back to the classic version of geth, using the --bootnodes option, and have been running it for about 8 hours now.  It is running very stable.  It stays synced, I'm not getting any of the error message in the log file, and internet usage is way down.  In case you're wondering, I used msornay's node from [this thread](https://github.com/ethereumproject/go-ethereum/issues/4) for my bootnode.

So I guess that means one or more of the 4 default bootnodes hard coded into the program are working on the wrong chain?

**Comment by Hou5e** [comment] 2016-08-06 14:37
Using the --bootnodes option fixed this issue for me as well. Thanks!

I was new to this, and only saw the download page, which doesn't mention that you should be using some command line options. So, I was just running the executable with no options originally, and getting the Bad block #1920000 error.

**Comment by yt-bg** [comment] 2016-08-08 08:30
**REPORT:** running for 3 days with default bootnodes and this problem hasn't appear

**Comment by whatisgravity** [comment] 2016-08-29 17:24
This should be resolved in the new 1.4.11 release now available. I tried to reproduce the issue and I was not able to. The issue can be reopen if someone reproduces it.

**Closed by whatisgravity** 2016-08-29 17:24 UTC
