### ISSUE TITLE
Hash geth-classic-v6.0.9-linux.tar.gz is different with .sha256

### ISSUE THREAD

**Issue by melvjoshua** [ethereumproject/go-ethereum#728] opened 2019-08-28 07:57 UTC
Are there any typo in geth-classic-v6.0.9-linux.sha256?

The hash value from geth-classic-v6.0.9-linux.sha256 is `005e755ca0840d5679d18af22d15a8f20a0a1f49939ae427f2ac7ed0de1b3`

When I hashed geth-classic-v6.0.9-linux.tar.gz with `sha256sum`, the value is `fca005e755ca0840d5679d18af22d15a8f20a0a1f49939ae427f2ac7ed0de1b3`

**Comment by soc1c** [comment] 2019-08-29 08:10
duplicate of https://github.com/etclabscore/go-ethereum/issues/50

**Closed by soc1c** 2019-08-29 08:10 UTC
