### ISSUE TITLE
Windows builds?

### ISSUE THREAD

**Issue by peterlayke** [ethereumproject/go-ethereum#730] opened 2019-09-09 04:59 UTC
Hi all, 

Running a private node and I see the team has stopped compiling Windows Builds?
With the hard fork looming so closely will there by a Windows build compiled?

**Comment by peterlayke** [comment] 2019-09-09 05:01
> Hi all,
> 
> Running a private node and I see the team has stopped compiling Windows Builds?
> With the hard fork looming so closely will there by a Windows build compiled?

NVM, I see the github page has moved to: https://github.com/etclabscore/go-ethereum/releases

**Comment by soc1c** [comment] 2019-09-09 10:07
duplicate of https://github.com/etclabscore/go-ethereum/issues/52

**Closed as completed by soc1c** 2019-09-09 10:07 UTC
