### ISSUE TITLE
Etc are not synchronized

### ISSUE THREAD

**Issue by HYHRainman** [ethereumproject/go-ethereum#725] opened 2019-08-26 06:49 UTC
2019-08-26 11:07:51 Local head header:     #0 [0xd4e567…] TD=17179869184
2019-08-26 11:07:51 Local head full block: #0 [0xd4e567…] TD=17179869184
2019-08-26 11:07:51 Local head fast block: #0 [0xd4e567…] TD=17179869184
2019-08-26 11:07:51 Starting server...
2019-08-26 11:07:51 UDP listening. Client enode: enode://844996f8db6420d527fefb08c35abec579ff8f9a7f91a1cca0d95ab6a83e1121c49bf8a2e9fc687ef500316189541d2da1afec932c75fc3faf6eb4d35753ba59@[::]:30306
2019-08-26 11:07:51 IPC endpoint opened: /home/lisuwen/wallet/etc/geth-classic-v6.0.8-linux/mainnet/geth.ipc
2019-08-26 11:07:51 HTTP endpoint: http://127.0.0.1:1234
2019-08-26 11:07:51 Debug log config: verbosity=5 log-dir=/home/lisuwen/wallet/etc/geth-classic-v6.0.8-linux/mainnet/log vmodule=*
2019-08-26 11:07:51 Display log config: display=3 status=sync=1m0s
2019-08-26 11:07:51 Machine log config: mlog=off
2019-08-26 11:08:51 Discover                                                                 0/25 peers
2019-08-26 11:09:51 Discover                                                                 0/25 peers
2019-08-26 11:10:51 Discover                                                                 0/25 peers
2019-08-26 11:11:51 Discover                                                                 0/25 peers
2019-08-26 11:12:51 Discover                                                                 0/25 peers
2019-08-26 11:13:51 Discover                                                                 0/25 peers
2019-08-26 11:14:51 Discover                                                                 0/25 peers
2019-08-26 11:15:51 Discover                                                                 0/25 peers

**Comment by GeekLic** [comment] 2019-08-26 07:21
I got the same question yet.It's really unbelieveable.

019-08-26 15:15:11 Geth Classic version: v6.0.8
2019-08-26 15:15:11 Blockchain: Ethereum Classic Mainnet
2019-08-26 15:15:11 Chain database: /root/.ethereum-classic/mainnet/chaindata
2019-08-26 15:15:11 Blockchain upgrades configured: 7
2019-08-26 15:15:11  1150000 Homestead
2019-08-26 15:15:11  1920000 The DAO Hard Fork (0x94365e3a8c0b35089c1d1195081fe7489b528a84b22199c916180db8b28ade7f)
2019-08-26 15:15:11  2500000 GasReprice
2019-08-26 15:15:11  3000000 Diehard
2019-08-26 15:15:11  5000000 Gotham
2019-08-26 15:15:11  5900000 Defuse Difficulty Bomb
2019-08-26 15:15:11  8772000 Atlantis
2019-08-26 15:15:11 Using 10 configured bootnodes
2019-08-26 15:15:11 Use Sputnik EVM: false
2019-08-26 15:15:11 No etherbase set and no accounts found as default
2019-08-26 15:15:11 Allotted 1024MB cache and 1024 file handles to /root/.ethereum-classic/mainnet/chaindata
2019-08-26 15:15:11 Allotted 16MB cache and 16 file handles to /root/.ethereum-classic/mainnet/dapp
2019-08-26 15:15:11 Protocol Versions: [63 62], Network Id: 1, Chain Id: 61
2019-08-26 15:15:12 Genesis block: 0xd4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3 (mainnet)
2019-08-26 15:15:12 Local head header:     #0 [0xd4e567…] TD=17179869184
2019-08-26 15:15:12 Local head full block: #0 [0xd4e567…] TD=17179869184
2019-08-26 15:15:12 Local head fast block: #0 [0xd4e567…] TD=17179869184
2019-08-26 15:15:12 Starting server...
2019-08-26 15:15:13 UDP listening. Client enode: enode://5dd14291f1fc9a657c7542453a22b9e46c00be4a0c0b31dc6804c25e98e63fe33a186c2aed360a677a44b9404a0f48970b4ef4a2cacfbc9fb9cc5812f313589d@[::]:30303
2019-08-26 15:15:13 HTTP endpoint: http://0.0.0.0:8545
2019-08-26 15:15:13 Debug log config: verbosity=5 log-dir=/root/.ethereum-classic/mainnet/log vmodule=*
2019-08-26 15:15:13 Display log config: display=3 status=sync=1m0s
2019-08-26 15:15:13 Machine log config: mlog=off
2019-08-26 15:15:13 IPC endpoint opened: /root/.ethereum-classic/mainnet/geth.ipc
2019-08-26 15:16:13 Discover                                                                 0/20 peers
2019-08-26 15:17:13 Discover                                                                 0/20 peers
2019-08-26 15:18:13 Discover                                                                 0/20 peers
2019-08-26 15:19:13 Discover                                                                 0/20 peers
2019-08-26 15:20:13 Discover                                                                 0/20 peers
2019-08-26 15:21:13 Discover                                                                 0/20 peers

**Comment by chunfuyang** [comment] 2019-08-26 09:01
> I got the same question yet.It's really unbelieveable.
> 
> 019-08-26 15:15:11 Geth Classic version: v6.0.8
> 2019-08-26 15:15:11 Blockchain: Ethereum Classic Mainnet
> 2019-08-26 15:15:11 Chain database: /root/.ethereum-classic/mainnet/chaindata
> 2019-08-26 15:15:11 Blockchain upgrades configured: 7
> 2019-08-26 15:15:11 1150000 Homestead
> 2019-08-26 15:15:11 1920000 The DAO Hard Fork (0x94365e3a8c0b35089c1d1195081fe7489b528a84b22199c916180db8b28ade7f)
> 2019-08-26 15:15:11 2500000 GasReprice
> 2019-08-26 15:15:11 3000000 Diehard
> 2019-08-26 15:15:11 5000000 Gotham
> 2019-08-26 15:15:11 5900000 Defuse Difficulty Bomb
> 2019-08-26 15:15:11 8772000 Atlantis
> 2019-08-26 15:15:11 Using 10 configured bootnodes
> 2019-08-26 15:15:11 Use Sputnik EVM: false
> 2019-08-26 15:15:11 No etherbase set and no accounts found as default
> 2019-08-26 15:15:11 Allotted 1024MB cache and 1024 file handles to /root/.ethereum-classic/mainnet/chaindata
> 2019-08-26 15:15:11 Allotted 16MB cache and 16 file handles to /root/.ethereum-classic/mainnet/dapp
> 2019-08-26 15:15:11 Protocol Versions: [63 62], Network Id: 1, Chain Id: 61
> 2019-08-26 15:15:12 Genesis block: 0xd4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3 (mainnet)
> 2019-08-26 15:15:12 Local head header: #0 [0xd4e567…] TD=17179869184
> 2019-08-26 15:15:12 Local head full block: #0 [0xd4e567…] TD=17179869184
> 2019-08-26 15:15:12 Local head fast block: #0 [0xd4e567…] TD=17179869184
> 2019-08-26 15:15:12 Starting server...
> 2019-08-26 15:15:13 UDP listening. Client enode: enode://5dd14291f1fc9a657c7542453a22b9e46c00be4a0c0b31dc6804c25e98e63fe33a186c2aed360a677a44b9404a0f48970b4ef4a2cacfbc9fb9cc5812f313589d@[::]:30303
> 2019-08-26 15:15:13 HTTP endpoint: http://0.0.0.0:8545
> 2019-08-26 15:15:13 Debug log config: verbosity=5 log-dir=/root/.ethereum-classic/mainnet/log vmodule=*
> 2019-08-26 15:15:13 Display log config: display=3 status=sync=1m0s
> 2019-08-26 15:15:13 Machine log config: mlog=off
> 2019-08-26 15:15:13 IPC endpoint opened: /root/.ethereum-classic/mainnet/geth.ipc
> 2019-08-26 15:16:13 Discover 0/20 peers
> 2019-08-26 15:17:13 Discover 0/20 peers
> 2019-08-26 15:18:13 Discover 0/20 peers
> 2019-08-26 15:19:13 Discover 0/20 peers
> 2019-08-26 15:20:13 Discover 0/20 peers
> 2019-08-26 15:21:13 Discover 0/20 peers

This issue has been fixed in Geth Classic v6.0.9-Stable Hot-Fix  https://github.com/etclabscore/go-ethereum/releases/tag/v6.0.9

**Comment by soc1c** [comment] 2019-08-26 16:11
Duplicate of https://github.com/etclabscore/go-ethereum/issues/49

**Closed by soc1c** 2019-08-26 16:11 UTC
