### ISSUE TITLE
Incorrect Filesystem error message

### ISSUE THREAD

**Issue by splix** [ethereumproject/go-ethereum#75] opened 2016-10-18 08:08 UTC
#### System information

Geth version: `geth 3.0.0`
OS & Version: Linux
#### Actual behaviour

When an FS for chaindata is mounted in read only is display wrong message _no space left on device_
#### Backtrace

```
I1018 07:54:33.444463 ethdb/database.go:83] Alloted 4096MB cache and 1024 file handles to /data/chaindata
Fatal: Could not open database: mkdir /data/chaindata: no space left on device
```

But:

```
$ df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/sdb        148G   37G  104G  27% /data
```

Most likely FS was mounted in read-only mode during Geth startup.

**Comment by mikeyb** [comment] 2016-10-18 14:46
Also may be worth checking there are sufficient inodes on that filesystem as well.

**Comment by mikeyb** [comment] 2017-01-25 21:18
Thinking about this more.  I think this error message is sufficient.  Technically there is no space left on a read only device (0 write-able bits). Geth should not be expected to diagnose read only file systems.  I would expect that error would send the end user on a path of finding the root cause of the system problem.

**Comment by whilei** [comment] 2017-05-04 21:25
Closing, since @mikeyb's last comment makes it seem like that's something he would want and I agree with him.

**Closed by whilei** 2017-05-04 21:25 UTC
Labels: type/bug
